# Importing Jupyter Notebooks as Modules

From basics to more sophisticated command for data visualisation
1. Basics python command
2. Numpy
3. Matplotlib


## Basics

In [1]:
#Exponentiation
print(4 ** 2)


16


In [7]:
#Types and converstion
mInt = 6
mFloat = .4
mString = "Hey"
mConversion = str(mFloat)
print (mInt, mFloat, mString, type(mConversion))

6 0.4 Hey <class 'str'>


### Lists

In [9]:
a = "is"
b = "nice"
my_list = [["my", "nested", "list"], a, b]
print (my_list)

[['my', 'nested', 'list'], 'is', 'nice']


In [14]:
print (my_list[-1],  " == ",  my_list [2])

nice  ==  nice


In [17]:
#Slicing and dicing
x = ["0", "1", "2", "3"]
print (x[1:3]) #end border is exclusif
print (x[:2])

['1', '2']
['0', '1']


In [30]:

x = [["a", "b", "c"],
     ["d", "e", "f"],
     ["g", "h", "i"]]
print(x[2][0])
print(x[2][:2])#Intersection of both index

g
['g', 'h']


In [31]:
x = x + [["j", "k", "l"]] #add a sublist with double [[]]
print (x)

[['a', 'b', 'c'], ['d', 'e', 'f'], ['g', 'h', 'i'], ['j', 'k', 'l']]


In [32]:
# Create areas_copy
X_pointer = x #Point to the same list (memory adress)
y = list(x)   #Y is an other list
del(x[1])
print (y)


[['a', 'b', 'c'], ['d', 'e', 'f'], ['g', 'h', 'i'], ['j', 'k', 'l']]


In [34]:
z = [11.25, 18.0, 20.0]
# Sort full in descending order: full_sorted
full_sorted = sorted (z, reverse=True)
# Print out full_sorted
print(full_sorted)

[20.0, 18.0, 11.25]


In [39]:
#Search index
print(z.index(20.0))
# Print out how often 14.5 appears in areas
print (z.count(18.0))

2
1


## Numpy: the fundamental package for scientific computing with Python

In [40]:
# Import the numpy package as np
import numpy as np

In [44]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]
# Create a Numpy array from baseball: np_baseball
np_baseball = np.array(baseball)
print (baseball)
print (np_baseball)

[180, 215, 210, 210, 188, 176, 209, 200]
[180 215 210 210 188 176 209 200]


In [45]:
#Perform operation on all datas
print (np_baseball * 10)

[1800 2150 2100 2100 1880 1760 2090 2000]


In [48]:
#Perform condition
print (np_baseball [np_baseball < 200]) #the conditition is creating an boolean array
#So we can get indexes from one np.array to slect value in a second one 

[180 188 176]


### 2d Numpy Array

In [50]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]
# Create a 2D Numpy array from baseball: np_baseball
np_baseball = np.array (baseball)
# Print out the shape of np_baseball
print (np_baseball.shape)

(4, 2)


In [54]:
# Print out the 4th row of np_baseball
print (np_baseball[3,:])
# Select the entire second column of np_baseball: np_weight
print (np_baseball[:,1])

[ 188.    75.2]
[  78.4  102.7   98.5   75.2]


In [55]:
#Appllying a filter on an array
conversion = np.array([10, 1000])
# Print out product of np_baseball and conversion
print ( np_baseball * conversion)

[[   1800.   78400.]
 [   2150.  102700.]
 [   2100.   98500.]
 [   1880.   75200.]]


## Some statistics tricks

In [57]:
# Print out the mean of height
print( np.mean(np_baseball[:,0]))
# Print out the median of weight
print( np.median(np_baseball[:,1]))

198.25
88.45


In [58]:
#Are these columns correlated ?
print(np.corrcoef(np_baseball[:,0],np_baseball[:,1]))

[[ 1.          0.95865738]
 [ 0.95865738  1.        ]]


# Matplotlib

In [59]:
import matplotlib.pyplot as plt